// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmoUUjH_U0Othzo9R9zatgQbwKMzTgJ-M',
    appId: '1:287336211777:web:2d078e9a769c9560c42dc0',
    messagingSenderId: '287336211777',
    projectId: 'smartreplies-4e187',
    authDomain: 'smartreplies-4e187.firebaseapp.com',
    storageBucket: 'smartreplies-4e187.appspot.com',
    measurementId: 'G-X6PFJCXL9H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWi8j-Mr-H6QW6GXL5_5UJlhTXBo99A20',
    appId: '1:287336211777:android:aa59a74606c50e44c42dc0',
    messagingSenderId: '287336211777',
    projectId: 'smartreplies-4e187',
    storageBucket: 'smartreplies-4e187.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd2ciIf7aKseKePtqn7NvZ4c0hyqfZZ5s',
    appId: '1:287336211777:ios:e5b08170b3e623dfc42dc0',
    messagingSenderId: '287336211777',
    projectId: 'smartreplies-4e187',
    storageBucket: 'smartreplies-4e187.appspot.com',
    iosClientId: '287336211777-s5hjie04jspprjp4idftjvkfh224rhcb.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartReplies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd2ciIf7aKseKePtqn7NvZ4c0hyqfZZ5s',
    appId: '1:287336211777:ios:e5b08170b3e623dfc42dc0',
    messagingSenderId: '287336211777',
    projectId: 'smartreplies-4e187',
    storageBucket: 'smartreplies-4e187.appspot.com',
    iosClientId: '287336211777-s5hjie04jspprjp4idftjvkfh224rhcb.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartReplies',
  );
}
